spring:
  application:
    name: SERVICE-HELLO

server:
  port: 8003

eureka:
  client:
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

#instance:
#  instance-id: eureka-client-8001
#  prefer-id-address: true
#
#info:
#  app.name: eureka-client
#  company.name: yizhang
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$